CREATE DATABASE IF NOT EXISTS app_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE app_db;

CREATE TABLE IF NOT EXISTS `item` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(100) NOT NULL,
	`descricao` VARCHAR(300) NOT NULL,
	`preco` DECIMAL(10, 2) NOT NULL,
	`tipo` ENUM('produto', 'servico') NOT NULL,
	`estoque` INTEGER NOT NULL,
	`categoria_id` INTEGER NOT NULL,
	`fornecedor_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `pedido` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`cliente_id` INTEGER NOT NULL,
	`preco_total` DECIMAL(10, 2) NOT NULL,
	`status` ENUM() NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `atendimento` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`data_atendimento` DATE NOT NULL,
	`item_pedido_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `item_pedido` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`pedido_id` INTEGER NOT NULL,
	`item_id` INTEGER NOT NULL,
	`quantidade` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `cliente` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(100) NOT NULL,
	`cpf` VARCHAR(16) NOT NULL,
	`cnpj` VARCHAR(16), NULL,
	`email` VARCHAR(100) NOT NULL,
	`endereco` VARCHAR(200) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `categoria` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `fornecedor` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(100) NOT NULL,
	`telefone` VARCHAR(18) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`endereco` VARCHAR(120) NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `pedido`
ADD FOREIGN KEY(`cliente_id`) REFERENCES `cliente`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `item_pedido`
ADD FOREIGN KEY(`pedido_id`) REFERENCES `pedido`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `item_pedido`
ADD FOREIGN KEY(`item_id`) REFERENCES `item`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `item`
ADD FOREIGN KEY(`categoria_id`) REFERENCES `categoria`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `item`
ADD FOREIGN KEY(`fornecedor_id`) REFERENCES `fornecedor`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;